language: csharp
sudo: false
dist: trusty
mono: none
dotnet: 1.0.4
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1   
os:
  - linux
  - osx
osx_image: xcode8.3
script:
  - if test "$TRAVIS_OS_NAME" == "linux"; then dotnet restore ~/solutions/cloudscribe.CustomRegistration.Kvp/cloudscribe.CustomRegistration.Kvp.sln; fi
  - if test "$TRAVIS_OS_NAME" == "osx"; then dotnet restore ~/solutions/cloudscribe.CustomRegistration.Kvp/cloudscribe.CustomRegistration.Kvp.sln --disable-parallel; fi
  - dotnet build ~/solutions/cloudscribe.CustomRegistration.Kvp/cloudscribe.CustomRegistration.Kvp.sln -c Release
